name: build

on:
  push:
    branches:
      - "*"

jobs:
  build-assets:
    name: Build WASM and JS files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.0
      - run: emcc --version
      - run: sudo apt install -y autoconf automake
      - run: ./build-rnnoise.sh

      # [注意] setup-emsdkが古いnode/npmをインストールしてしまうので、
      #        setup-nodeはその後に呼び出す必要がある。
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run build
      - name: "Commit docs"
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch origin docs
          git switch -c docs origin/docs || git switch docs
          git add -f dist
          git commit --amend --reset-author --no-edit
          git push -f
