name: test

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16']
    steps:
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.0
      - run: emcc --version
      - run: sudo apt install -y autoconf automake
      - run: ./build-rnnoise.sh

      # [注意] setup-emsdkが古いnode/npmをインストールしてしまうので、
      #        setup-nodeはその後に呼び出す必要がある。
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - run: npm run test
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: media-processors
          SLACK_COLOR: danger
          SLACK_TITLE: Failure test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
